### ISSUE TITLE
How about to use a flexible amount of scans that can be displayed on the page?

### ISSUE THREAD

**Issue by tiokim** [Samsung/LPVS#221]
How about to use a flexible amount of scans that can be displayed on the page?

For example:
![image](https://github.com/Samsung/LPVS/assets/45031201/0a4fcaed-b5fa-4ed2-8d9e-5412c82c2ac3)

_Originally posted by @o-kopysov in https://github.com/Samsung/LPVS/pull/220#discussion_r1336098813_

**Comment by quswjdgma83** [comment]
Great idea, I'm trying to give option values of 5, 10, 20, and 50 by drop down, would that be okay?

**Comment by o-kopysov** [comment]
> Great idea, I'm trying to give option values of 5, 10, 20, and 50 by drop down, would that be okay?

I agree with your proposal.

**Comment by quswjdgma83** [comment]
Thank you for your opinion 👍
