### ISSUE TITLE
Add `throw Exception` in case of error

### ISSUE THREAD

**Issue by o-kopysov** [Samsung/LPVS#301]
In `LPVSWebhookUnit` in some functions, instead of returning an error message as String, we have to throw an exception.
Example is here: https://github.com/Samsung/LPVS/blob/f26543d676b30a94900b20e74da25e3c9f166948/src/main/java/com/lpvs/util/LPVSWebhookUtil.java#L94

UTs should be updated as well

**Comment by choichanhyeok** [comment]
Hi @o-kopysov

I'm interested in contributing this project, particularly regarding Issue #301. Would it be alright if I worked on this issue?

Looking forward to your guidance.

Thanks,

**Comment by o-kopysov** [comment]
Hello, @choichanhyeok .

Sure. Just want to point out that unit tests should also be fixed 😁

Thanks!
