### ISSUE TITLE
Exception when add empty PR or PR that contains text file only

### ISSUE THREAD

**Issue by o-konoval** [Samsung/LPVS#304]
**Describe the bug**
Exception appeared when add empty PR or PR that contains text file only.
Empty PR- for example PR that contains 3 spaces & 3 CR. Or adding 3 spaces & 3 CR to exist file.
Examples of text files in attachments:

[example.txt](https://github.com/Samsung/LPVS/files/13319231/example.txt)

[README.md](https://github.com/Samsung/LPVS/files/13319243/README.md)

Input data:
TITLE_SC="How to build and run LPVS from source code";
TITLE_SET_PROJ="Setting up your project to interact with LPVS";
MANUAL=https://github.com/Samsung/LPVS/blob/main/README.md

**To Reproduce**
1.Follow steps 1-4 of TITLE_SC of MANUAL;
2.Check log of execution of LPVS Java application;
3.Follow steps 1-2 of TITLE_SET_PROJ of MANUAL;
4.Check ngrok started in terminal successfully.
****

For empty PR:
5.Make PR with adding new file in repo that contains: 3 spaces & 3CR ;

For text file1:
5.Make PR with adding new file in repo from attachment1 (example.txt) above;

For text file2:
5.Make PR with adding new file in repo from attachment2(README.md) above;

****
6.Check message in PR;
7.Check terminal of ngrok execution after PR;
8.Check log of LPVS Java application after PR.

**Expected behavior**
1.Steps 1-4 of TITLE_SC of MANUAL done;
2.Log of execution of LPVS Java application is ok;
3.Steps 1-2 of TITLE_SET_PROJ of MANUAL done;
4.Application ngrok started in terminal and log is ok.
5.PRs with adding spaces&CRs or text files done;
6.Message in PR and log is ok;
7.Terminal of ngrok execution after PR and log is ok;
8.Log of LPVS Java application is ok.

**Screenshots**
Real logs for empty PR:
[empty_build_from_source.txt](https://github.com/Samsung/LPVS/files/13319347/empty_build_from_source.txt)

Real logs for text PR:
[text_build_from_source.txt](https://github.com/Samsung/LPVS/files/13319349/text_build_from_source.txt)

**Test environment configuration (please complete the following information):**
* Java: (openjdk version "11.0.20.1" 2023-08-24)
* LPVS Release: (1.2.0- commit f26543d)
* MySQL Server version: 8.0.35-0ubuntu0.22.04.1 (Ubuntu)

**Additional context**
Previously problem existed only for empty PR case.

**Comment by m-rudyk** [comment]
LPVS is using scanoss service to run scan via separate process. 

The control of this process is performed by Java ProcessBuilder and we have limited functionality over that.
below is example output of running scan on  text folder: 
`
 scanoss-py scan --debug --no-wfp-output -o /home/shik/Projects/Debug_LPVS/ff4ec4b5ac3babe84b0de55c85de014ca5d5eff0/result.json, /home/shik/Projects/Debug_LPVS/ff4ec4b5ac3babe84b0de55c85de014ca5d5eff0
Scan Files
Scan Snippets
Setting up (secure: True) connection to scanoss.com:443...
Writing results to /home/shik/Projects/Debug_LPVS/ff4ec4b5ac3babe84b0de55c85de014ca5d5eff0/result.json,...
Searching /home/shik/Projects/Debug_LPVS/ff4ec4b5ac3babe84b0de55c85de014ca5d5eff0 for files to fingerprint...
F Root: /home/shik/Projects/Debug_LPVS/ff4ec4b5ac3babe84b0de55c85de014ca5d5eff0, Dirs: ['text_files'], Files ['result.json,']
F Root: /home/shik/Projects/Debug_LPVS/ff4ec4b5ac3babe84b0de55c85de014ca5d5eff0/text_files, Dirs: [], Files []
Warning: No files found to scan in folder: /home/shik/Projects/Debug_LPVS/ff4ec4b5ac3babe84b0de55c85de014ca5d5eff0
`

This result to exitCode (1) with no error description.
Code snippet that handles this exit code:
`
            if (status == 1) {
                log.error("Scanoss scanner terminated with none-zero code. Terminating.");
                BufferedReader output = null;
                try {
                    output =
                            new BufferedReader(
                                    new InputStreamReader(process.getErrorStream(), "UTF-8"));
                    log.error(output.readLine());
                    throw new Exception(
                            "Scanoss scanner terminated with none-zero code. Terminating.");
`
Actual log error message:
`
2023-11-10 15:17:04.103 ERROR 94138 --- [  LPVS-ASYNC::1] c.l.s.s.s.LPVSScanossDetectService       : Scanoss scanner terminated with none-zero code. Terminating.
2023-11-10 15:17:04.103 ERROR 94138 --- [  LPVS-ASYNC::1] c.l.s.s.s.LPVSScanossDetectService       : null
2023-11-10 15:17:04.126 ERROR 94138 --- [  LPVS-ASYNC::1] com.lpvs.service.LPVSQueueService        : Can't authorize commentResults() java.lang.Exception: Scanoss scanner terminated with none-zero code. Terminating.
`

On the cntrary, when we have code files, the process finishes with exit code 0 and no error handling required. 



The only  solution that I can suggest:
1. based on console output: "No files found to scan in folder:", we can ommit terminating LPVS scan
2. Suggest change to "scanoss" repo not to exit with error in case of empty folder

**Comment by m-rudyk** [comment]
If we use Scanoss with option "--all-extensions", this text files will be scanned with successfull finalization. It may impact on scan time and LPVS performance.

**Comment by o-kopysov** [comment]
@m-rudyk  First, let's try to apply `--all-extensions` option and measure performance. I think there will be no issues with this option.
