### ISSUE TITLE
Javadoc comments extension

### ISSUE THREAD

**Issue by o-kopysov** [Samsung/LPVS#307]
To improve the project documentation, we need to cover all packages with Javadoc comments. 

- [x] config
- [x] entity
- [x] exception
- [x] repository
- [ ] service
- [x] util

**Comment by o-kopysov** [comment]
Added #315  for some packages.

**Comment by choichanhyeok** [comment]
Hi @o-kopysov

I'm interested in contributing this project, particularly regarding Issue #307. Would it be alright if I worked on this issue?

Looking forward to your guidance.

Thanks,

**Comment by o-kopysov** [comment]
Hello, @choichanhyeok .

Your contribution is very welcome!

Some packages are already covered by comments (please refer to PR #315).

Please focus on remaining files 😉

Thanks!
