### ISSUE TITLE
Integrate LPVS as a GitHub Action and Publish to GitHub Marketplace

### ISSUE THREAD

**Issue by o-kopysov** [Samsung/LPVS#319]
In this task, we aim to streamline and enhance user workflow by implementing LPVS as a GitHub Action. 

**Objectives:**

- [ ] GitHub Action Integration:

Configure LPVS to run as a GitHub Action, ensuring seamless execution within the repository.
Define workflow steps for LPVS to fit into your CI/CD pipeline seamlessly.

- [ ] Parameterization and Customization:

Allow users to customize LPVS configurations through GitHub Action parameters, ensuring flexibility for various use cases.
Provide clear documentation for customization options to empower users.

- [ ] Testing and Validation:

Implement thorough testing to ensure the reliability and consistency of LPVS within the GitHub Action environment.
Validate the integration across different scenarios to guarantee robust functionality.

- [ ] GitHub Marketplace Submission:

Prepare the necessary artifacts and documentation for submission to the GitHub Marketplace.
Follow GitHub's guidelines for Marketplace submissions to ensure a smooth review process.

**Comment by tiokim** [comment]
When it comes to the Github Marketplace submission, I don't know the difference from [scanoss.app](https://github.com/marketplace/scanoss-app) and feel that it is not our role.

**Comment by tiokim** [comment]
> 1. We can offer github action. Unlike the application, it does not require installation by the organization leader.

After #300 merged, It seems good to make how to use LPVS for github action!
