### ISSUE TITLE
Optimise dababase dump for both creating local database and running single scan

### ISSUE THREAD

**Issue by m-rudyk** [Samsung/LPVS#331]
## Feature Request

**Description:**
Currently, project uses 2 dump files for:
 - creating new database for running local scans;
 - baseless single scan operations

**Use Case:**
[Optimise dump file](https://github.com/Samsung/LPVS/pull/300/files#r1410530075) to use same for both operations

**Additional Information:**

**Comment by v-kerimov** [comment]
Looked into the problem. At the same time found some errors in the application-singlescan.properties file that need fixing. The solution is almost arrived at.
It is possible to remove schema.sql and data.sql can be renamed as whatever, including database_dump.sql.
