### ISSUE TITLE
Refactoring of `LPVSTableConfiguration`

### ISSUE THREAD

**Issue by o-kopysov** [Samsung/LPVS#369]
## Task

**Description:**
In `util` directory, there is an `LPVSTableConfiguration` class. We need to decide whether we need it or not.
Afer that, we have to do a refactoring of this class.

**Comment by m-rudyk** [comment]
This class can be removed.

**Comment by o-kopysov** [comment]
> This class can be removed.

OK. Please prepare the corresponding PR.
