### ISSUE TITLE
LGTM.com will be shut down

### ISSUE THREAD

**Issue by tiokim** [Samsung/LPVS#38]
CodeQL is enough to analysis LPVS.
Please refer to their [blog article](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/).

**Comment by MoonkiHong** [comment]
Great. I love this opinion. @tdrozdovsky It is your turn. What do you think? 😄

**Comment by tdrozdovsky** [comment]
While trying to understand (reason is not clear to me)

**Comment by o-kopysov** [comment]
AFAIU after the reading of all materials, CodeQL is doing the same as LGTM.
So, let's disable LGTM for LPVS.
@tdrozdovsky  do you agree? If Yes, please disable LGTM.
