### ISSUE TITLE
Container Image Distribution

### ISSUE THREAD

**Issue by t25kim** [Samsung/LPVS#5]
It must be great if we distribute LPVS container image from the registry.
Which registry do you prefer? Docker Hub? or Github Container Registry?

**Comment by o-kopysov** [comment]
@t25kim 
It's a good idea. Let's use the same approach as for the LF Home Edge project.

@tdrozdovsky  could you please share your opinion?

**Comment by MoonkiHong** [comment]
When it comes to LF Edge, the Dockerhub is complimentary since its host organization is _Open Source Initiative (The Linux Foundation)_. It would be good for us if we could refer to the same when it comes to the project hosted by _Samsung Electronics_

**Comment by o-kopysov** [comment]
@t25kim 
We are working on this ticket.
We will prepare the GitHub Actions auto-deploy script.

**Comment by o-kopysov** [comment]
@tdrozdovsky 
Please share the current progress with us.
