### ISSUE TITLE
LPVS release 1.0.1

### ISSUE THREAD

**Issue by o-kopysov** [Samsung/LPVS#51]
It's time to plan the new release of LPVS.
It will include a lot of updates compared with v1.0.0:
- possibility to set keys from env. or via command line (PR #39 )
- improved code coverage (our goal is 70%)
- updated policies and readme
- fixed all alerts, code quality issues, and build warnings

After the release, we will provide the docker image in the [Package section](https://github.com/orgs/Samsung/packages?repo_name=LPVS)

Opened questions:
1. Which new version should we assign: 1.0.1 or 1.1.0? 
My personal preference - 1.1.0, because we added new functionality - command line arguments
2. tbd

**Comment by t25kim** [comment]
I think `1.0.1` is fine now. It would be nice to increase the minor number if some new features are implemented.

**Comment by MoonkiHong** [comment]
I love @t25kim opinion. In the end, we need a policy for semantic versioning.
