### ISSUE TITLE
OpenSSF best practices badge

### ISSUE THREAD

**Issue by o-kopysov** [Samsung/LPVS#6]
Our goal is to achieve the Best Practice Passing badge.
The link to the LPVS project: https://bestpractices.coreinfrastructure.org/en/projects/6309

We will try to meet all goals from the checklist ASAP.

**Comment by MoonkiHong** [comment]
Wonderful suggestion!

**Comment by o-kopysov** [comment]
Current status is 90% for "Passing" badge ([link](https://bestpractices.coreinfrastructure.org/en/projects/6309)).
Missing items: Static code analysis, Dynamic code analysis
Sonar Cloud could help to solve all problems. But if its usage is impossible, we will try to find other ways to solve the problem.

**Comment by o-kopysov** [comment]
https://bestpractices.coreinfrastructure.org/en/projects/6309
