### ISSUE TITLE
Planning next LPVS release (1.0.2)

### ISSUE THREAD

**Issue by o-kopysov** [Samsung/LPVS#63]
Let's start to plan the next LPVS feature set.
Internally we discussed that it could be good if we provide the possibility for developers to use LPVS as a **GitHub Action step**.
We are investigating such a possibility, but first of all, I would like to ask your opinion about the idea.

**Comment by tdrozdovskiy** [comment]
Oleg spoke very softly. This is a great idea and the only right one.
P.S. I have some experience on how to do this.

**Comment by t25kim** [comment]
Currently, LPVS only uses SCANOSS server. I'm a little bit worried about unintended noise if we make it as Github Action instead of SCANOSS. 
You can see SCANOSS webhook and github app for more information.
- https://github.com/marketplace/scanoss-app
- https://github.com/scanoss/webhook

**Comment by o-kopysov** [comment]
@tiokim  I think we have to connect LPVS with DB to store all scan data.
I've prepared DB schema https://dbdiagram.io/d/63bce0c86afaa541e5d164f1
Please take a look on it. Your feedback is very meaningful for us.

**Comment by tiokim** [comment]
@o-kopysov Thanks for sharing DB schema.
The first impression is a little bit complicated and it would be great if we make it simple.
- `queue` seems good but it would be better if it is independent from other tables. 
We can save the information by parsing the PR event consisting of JSON to `queue` before processing the scanner operation.
If `worker` successfully processes it, it can be deleted from `queue`.
- I think `pull_requests` and `detected_issues` are enough for processed information. 
`pull_requests` should have necessary variables currently in other tables such as `url` from `repositories`.
`detected_issues` is same. It should have file and conflict license information.

**Comment by o-kopysov** [comment]
@tiokim  I've simplified the diagram according to your request. Please let me know your opinion. New url is https://dbdiagram.io/d/63c52e7f296d97641d79eaba

**Comment by tiokim** [comment]
@o-kopysov It looks awesome! 
I would like to add attributes below.
- `status` at queue : queued, running, success
- `component_lines` at detected_issues : range of lines in terms of component

**Comment by o-kopysov** [comment]
@tiokim I Agree with your proposal. The diagram is updated.

**Comment by tiokim** [comment]
@o-kopysov LGTM! Thanks for your hard work!

**Comment by o-kopysov** [comment]
@tiokim @MoonkiHong 
I propose to use SQLite DB in LPVS.
According to the guidelines [1](https://www.baeldung.com/spring-boot-sqlite) and [2](https://fullstackdeveloper.guru/2020/05/01/how-to-integrate-sqlite-database-with-spring-boot/), SQLite looks promising, but it differs from MySQL server which is used internally. 
I think that our goal is to use similar LPVS implementation internally and externally. 
So, I would be grateful for your opinion regarding this question.

**Comment by tiokim** [comment]
@o-kopysov Thanks for your suggestion.
I don't think SQLite is suitable for LPVS since it is not implemented for server. 
IMHO, it seems good to use MySQL or PostgreSQL for the first DB.

**Comment by MoonkiHong** [comment]
> @o-kopysov Thanks for your suggestion. I don't think SQLite is suitable for LPVS since it is not implemented for server. IMHO, it seems good to use MySQL or PostgreSQL for the first DB.

I am on the same page with @tiokim.

**Comment by m-rudyk** [comment]
@o-kopysov , latest version looks less tangled. As we talked before, please check if we can ommit branch field (pull request includes this information). Otherwise, looks good.

**Comment by tiokim** [comment]
I prefer separate containers, second one!
