### ISSUE TITLE
Apply code checkers to the project

### ISSUE THREAD

**Issue by o-kopysov** [Samsung/LPVS#7]
Please apply all the code checkers like Sonar to the repository code.
Also, please add all status badges to the main page.

**Comment by MoonkiHong** [comment]
@tdrozdovsky @o-kopysov What about only relying on CodeQL analysis instead of integrating the SonarCloud as well? Any concern on this?

**Comment by o-kopysov** [comment]
No objections from my side.

**Comment by tdrozdovsky** [comment]
CodeQL analysis and SonarCloud have different purposes and cannot be interchanged

**Comment by MoonkiHong** [comment]
Uhm. My point is not a way of interchaging SonarCloud to CodeQL. It is to firstly focus on the integration with CodeQL and let us clarify more if there is any potential issue to use SonarCloud to github.com/samsung/lpvs in terms of billing.

**Comment by tdrozdovsky** [comment]
@MoonkiHong I completely agree with you!

**Comment by tdrozdovsky** [comment]
https://sonarcloud.io/pricing?gads_campaign=Europe-1-SonarClouds&gads_ad_group=SonarCloud&gads_keyword=sonarcloud&gclid=Cj0KCQjw_7KXBhCoARIsAPdPTfgj0GjVJrij_X3KFZtCd8ivlCjSDTZyAHdkLd2uKJ1q7tagnfEUab4aAsfNEALw_wcB

**Comment by MoonkiHong** [comment]
Yeah.. I have recognized it. The point is that it is a bit ambiguous if others might think of LPVS under Samsung, not an open source..
